// This file is auto-generated by Terraform and uploaded to S3.
// For local development, replace the URL with your deployed API Gateway endpoint.
const API_BASE_URL = "https://2j7n5a3ppg.execute-api.us-east-1.amazonaws.com";
